Feature NXBT-1517 http compression
nuxeo/nuxeo-connect pull request #11
Opened 2017-02-01 13:26 UTC by yjulienne-nuxeo

2017-02-01 13:27 UTC, nuxeojenkins commented
From the blame information on this pull request, potential reviewers: @jcarsique, @tmartins, @mguillaume

2017-02-01 13:46 UTC, pgmillon commented
Hello,
according to the JIRA and as it seems to me most of this code is to match with the HttpClient upgrade, the latter is enough to have compressed communications between nuxeoctl & Connect, right ?

2017-02-01 13:59 UTC, efge requested changes

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/AbstractConnectConnector.java
> +        ConnectServerResponse response = execCall(url);
It's clearer to have the `try` _immediately_ after the call allocating a resource that needs to be released in a `finally` block. So move the `PackageDescriptor pkg = null` one line up.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/AbstractConnectConnector.java
> +                return result;
It's confusing to have this `return result` here and another one at a different level outside the `try`. Either put the whole logic in a `if (json != null)` and just keep the last `return result`, or move the last `return result` before the `catch`.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/http/ConnectHttpConnector.java
> +                log.warn("Unable to close Nuxeo Connect Server stream", e);
You can use `IOUtils.closeQuietly` instead. I don't think there's a legitimate case where we'd be interested in the error log on `close`.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/http/ConnectHttpResponse.java
> +            return EntityUtils.toString(entity);
`return entity == null ? null : EntityUtils.toString(entity)`

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/http/ConnectHttpResponse.java
> +            throw new ConnectServerError("Unable to close connexion resources", e);
connexion -> connection

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/http/proxy/NashornProxyPacResolver.java
> +                        new HttpGet(ConnectUrlConfig.getProxyPacUrl()))) {
You can have a single `try ()` with several `;`-separated resource allocation statements in it.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/http/proxy/NashornProxyPacResolver.java
> +                        throw new IOException("Unable to get pac file");
`+ httpResponse.getStatusLine()` in the exception message for better diagnostics.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +            log.debug(e, e);
If it fails nobody will see this. Just rethrow as a `RuntimeException`.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +                    getHttpClientContext(url, login, password))) {
Move `method` declaration outside the `try` and collapse the two `try` into one.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +                        return result;
Same comments as before about the two `return result`.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +            method.setEntity(new UrlEncodedFormEntity(nvps));
Move `method` up and collapse the two `try`.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +                    log.error("Unhandled response code: " + rc);
I'd prefer an exception I think.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +            try (CloseableHttpResponse httpResponse = httpClient.execute(method,
Collapse two `try`

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +                    log.error("Unhandled response code: " + rc);
Here also an exception would allow better diagnostics.

2017-02-01 13:59 UTC, efge commented on nuxeo-connect-client/src/test/java/org/nuxeo/connect/connector/http/TestConnectHttpConnector.java
> +        server.destroy();
Do the `server` cleanup in a `finally` block as we really want to release the server port even if the `for` loop has an error for some reason.

2017-02-01 17:22 UTC, yjulienne-nuxeo reviewed
@pgmillon yes exactly !

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/AbstractConnectConnector.java
> +        ConnectServerResponse response = execCall(url);
done

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/AbstractConnectConnector.java
> +                return result;
done

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/http/ConnectHttpConnector.java
> +                log.warn("Unable to close Nuxeo Connect Server stream", e);
done ! Also replaced `catch (Throwable t)` by `catch (IOException e)`

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/http/ConnectHttpResponse.java
> +            return EntityUtils.toString(entity);
done

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/http/ConnectHttpResponse.java
> +            throw new ConnectServerError("Unable to close connexion resources", e);
done

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/http/proxy/NashornProxyPacResolver.java
> +                        new HttpGet(ConnectUrlConfig.getProxyPacUrl()))) {
done

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/connector/http/proxy/NashornProxyPacResolver.java
> +                        throw new IOException("Unable to get pac file");
done

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +            log.debug(e, e);
done

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +                    log.error("Unhandled response code: " + rc);
A real treatment for each response code should be done, but for now raising a runtime exception with the same message will bring nothing to the user

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +            try (CloseableHttpResponse httpResponse = httpClient.execute(method,
done

2017-02-01 17:22 UTC, yjulienne-nuxeo commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/registration/RegistrationHelper.java
> +                    log.error("Unhandled response code: " + rc);
I keep it for now for same reason as before

2017-02-06 10:57 UTC, efge approved these changes

2017-02-06 10:57 UTC, efge commented
👍

2017-02-06 11:00 UTC, pgmillon commented
👍

2017-02-06 11:01 UTC, merged