NXP-29794: Allow SNAPSHOT references only if installed or explicitly …
nuxeo/nuxeo-connect pull request #42
Opened 2020-11-16 17:42 UTC by yjulienne-nuxeo

…required during dependency resolution

2020-11-16 17:43 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29794](https://jira.nuxeo.com/browse/NXP-29794): Resolve downstream Nuxeo Package versions from the requested resolved versions

2020-11-16 17:54 UTC, efge commented
Is it possible to add a unit test?

2020-11-17 13:58 UTC, jcarsique approved these changes
Reading the code, I understand that a package dependency won't be a SNAPSHOT unless it is explicitly requested by the root command (!= required by dependencies) or its parent is itself a SNAPSHOT. 
That looks pretty good to me, although I'm not sure that it does not change the behavior: what happens if a non SNAPSHOT package explicitly requires a SNAPSHOT package?

Can we confirm the fix with a unit test on nuxeo-connect side ? 

https://github.com/nuxeo/nuxeo/compare/fix-NXP-29794-pkg-snapshot-dependency-resolution LGTM :+1: 
The unit tests may be missing some use cases described in the ticket. 
I would add at least the two failing resolutions and a bunch of others to prevent regression and get a larger coverage:
- universe with A1, A2S (SNAPSHOT), B1, B2S
- dependency can be strict (A1 -> B1) or less (A1 -> B1+)
- request can be by name (mp-install A) or by version (mp-install A1)
- snapshot can be allowed or not
- bonus: what if A3 (not SNAPSHOT) depends on B3S ?

2020-11-18 16:33 UTC, efge requested changes

2020-11-18 16:33 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/packages/PackageManagerImpl.java
> +                        "Couldn't order %s missing %s (you may consider to relax or allow snapshots).", listToOrder,
`consider to` is bad English. Maybe instead say `consider using --relax true or --snapshot`?

2020-11-18 16:45 UTC, efge approved these changes

2020-11-19 13:58 UTC, jcarsique approved these changes

2020-11-19 13:58 UTC, jcarsique approved these changes

2020-11-19 13:59 UTC, merged