NXBT-3441: Fix target platform pattern matching when build number is 0
nuxeo/nuxeo-connect pull request #43
Opened 2020-11-18 16:51 UTC by yjulienne-nuxeo

2020-11-18 16:51 UTC, nuxeojenkins commented
View issue in JIRA: [NXBT-3441](https://jira.nuxeo.com/browse/NXBT-3441): Fix Target Platform matching with 0 as build number

2020-11-18 17:03 UTC, kevinleturc approved these changes

2020-11-18 17:03 UTC, efge requested changes

2020-11-18 17:03 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/packages/dependencies/TargetPlatformFilterHelper.java
> +            })) {
```suggestion
            if (possibleStringForms.stream().anyMatch(tpString -> FilenameUtils.wildcardMatch(tpString, target, IOCase.INSENSITIVE))) {
```

2020-11-18 17:03 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/packages/dependencies/TargetPlatformFilterHelper.java
> +    private static Set<String> getPossibleStringForms(PlatformId targetPlatform) {
You could make this `protected` and have unit tests (in the same Java package) that directly check the expansion. Or make it `public` even. But direct unit tests are good. Frankly without them I don't know what this method does...

2020-11-18 17:03 UTC, efge commented on nuxeo-connect-client/src/main/java/org/nuxeo/connect/packages/dependencies/TargetPlatformFilterHelper.java
> +            boolean hasQualifier = !StringUtils.isBlank(qualifier);
`!StringUtils.isBlank` -> `StringUtils.isNotBlank`

2020-11-18 17:45 UTC, efge requested changes

2020-11-18 17:45 UTC, efge commented on nuxeo-connect-client/src/test/java/org/nuxeo/connect/packages/dependencies/TargetPlatformFilterHelperTest.java
> +package org.nuxeo.connect.packages.dependencies;
Missing copyright header

2020-11-18 17:45 UTC, efge commented on nuxeo-connect-client/src/test/java/org/nuxeo/connect/packages/dependencies/TargetPlatformFilterHelperTest.java
> +                                                                         "test-0.0.0");
Could you create and use a small helper method to reduce the test repetitions:
```
public static void assertPossibleStringForms(String version, String... expected) {
        assertThat(getPossibleStringForms( //
                  PlatformId.of("test", new PlatformVersion(version)))) //
                                                                   .containsExactlyInAnyOrder(expected);
}
```

2020-11-19 14:05 UTC, jcarsique approved these changes

2020-11-19 14:24 UTC, merged